GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'RF'
  SESSION: 'RFormer'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 2
  NUM_EPOCHS: 100
#batch 4
  

#TRAINING:
 # TRAIN_PS: 128
  #TRAIN_DIR: './datasets/train_dataset/' # path to training data
  #VAL_DIR: './datasets/train_dataset/'     # path to validation data
  #SAVE_DIR: './checkpoints/'        # path to save models and images
  #SAVE_IMAGES: False
TRAINING:
  TRAIN_PS: 256
  TRAIN_DIR: '/content/Real-Fundus/datasets/train/'
  VAL_DIR: '/content/Real-Fundus/datasets/val/'
  SAVE_DIR: '/content/Real-Fundus/checkpoints/'
  SAVE_IMAGES: False

